import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.dev.joinworth.com/');
  await page.getByRole('link', { name: 'GET MY SCORE' }).click();
  await page.getByRole('button', { name: 'Continue with email' }).click();
  await page.getByPlaceholder('Enter email id').click();
  await page.getByPlaceholder('Enter email id').fill('kratika.gore+1607@joinworth.com');
  await page.getByPlaceholder('Enter email id').press('Enter');
  await page.getByPlaceholder('Enter first name').fill('k');
  await page.getByPlaceholder('Enter first name').click();
  await page.getByPlaceholder('Enter first name').fill('krati');
  await page.getByPlaceholder('Enter first name').press('Tab');
  await page.getByPlaceholder('Enter last name').fill('gore');
  await page.getByPlaceholder('Enter new password').click();
  await page.getByPlaceholder('Enter new password').press('CapsLock');
  await page.getByPlaceholder('Enter new password').fill('W');
  await page.getByPlaceholder('Enter new password').press('CapsLock');
  await page.getByPlaceholder('Enter new password').fill('Winjit@123');
  await page.getByPlaceholder('Confirm password').click();
  await page.getByPlaceholder('Confirm password').press('CapsLock');
  await page.getByPlaceholder('Confirm password').fill('W');
  await page.getByPlaceholder('Confirm password').press('CapsLock');
  await page.getByPlaceholder('Confirm password').fill('Winjit@123');
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('.w-8').first().click();
  await page.locator('.w-8').first().click();
  await page.locator('.w-8').first().click();
  await page.locator('.w-8').first().fill('4');
  await page.locator('input:nth-child(2)').fill('2');
  await page.locator('input:nth-child(3)').fill('9');
  await page.locator('input:nth-child(4)').fill('4');
  await page.locator('input:nth-child(5)').fill('8');
  await page.locator('input:nth-child(6)').fill('2');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByPlaceholder('Enter Tax ID Number (TIN)').click();
  await page.getByPlaceholder('Enter Tax ID Number (TIN)').fill('345676898');
  await page.getByPlaceholder('Enter company name').click();
  await page.getByPlaceholder('Enter company name').fill('us');
  await page.getByText('U.S. Bank Stadium').click();
  await page.getByRole('button', { name: 'Validate' }).click();
  await page.getByLabel('Industry*').click();
  await page.getByText('Agriculture, Forestry, Fishing and Hunting').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Connect' }).click();
  await page.frameLocator('iframe[title="Plaid Link"]').getByRole('button', { name: 'Continue' }).click();
  await page.frameLocator('iframe[title="Plaid Link"]').getByLabel('Citizens Bank').click();
  await page.frameLocator('iframe[title="Plaid Link"]').getByPlaceholder('User ID').click();
  await page.frameLocator('iframe[title="Plaid Link"]').getByLabel('User ID').click();
  await page.frameLocator('iframe[title="Plaid Link"]').getByLabel('User ID').fill('user_goog');
  await page.frameLocator('iframe[title="Plaid Link"]').getByLabel('User ID').press('Tab');
  await page.frameLocator('iframe[title="Plaid Link"]').getByLabel('Password').click();
  await page.frameLocator('iframe[title="Plaid Link"]').getByPlaceholder('User ID').fill('user_good');
  await page.frameLocator('iframe[title="Plaid Link"]').getByPlaceholder('Password').fill('pass');
  await page.frameLocator('iframe[title="Plaid Link"]').getByLabel('Password').fill('pass_good');
  await page.frameLocator('iframe[title="Plaid Link"]').getByRole('button', { name: 'Submit' }).click();
  await page.frameLocator('iframe[title="Plaid Link"]').getByRole('button', { name: 'Continue' }).click();
  await page.frameLocator('iframe[title="Plaid Link"]').getByRole('button', { name: 'Allow' }).click();
  await page.getByLabel('Title*').click();
  await page.getByRole('option', { name: 'Partner', exact: true }).click();
  await page.getByPlaceholder('Enter first name').click();
  await page.getByPlaceholder('Enter first name').fill('\tLeslie');
  await page.getByPlaceholder('Enter first name').click();
  await page.getByPlaceholder('Enter first name').fill('');
});